### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by r-tron18**
Little changes in the code repo.

### CODE REVIEW

**Comment by r-tron18** [comment]
Also i may recommend using a 6 digit otp for security

**Comment by sumit-badsara** [comment]
@r-tron18 Minor changes doesn't signify anything specific. Make the message more specific.

**Review by sumit-badsara — CHANGES_REQUESTED** [review]
It is still wrong, correct it to CampusAmbassador. Change the name of model too.

**Comment by sumit-badsara** [comment]
> Also i may recommend using a 6 digit otp for security

Yes, i have put up a poll on our slack channel, we will do it as majority suggests.

**Comment by r-tron18** [comment]
> @r-tron18 Minor changes doesn't signify anything specific. Make the message more specific.

Well the changes are viewable in pull request. But here are they.  added more files/folders in gitignore to ignore. changes readme so that the user cloning git now has to run python manage.py makemigrations and changed few things in users.model. As requested i will change CampusmbasadorProfile to CampusAmbasadur.

**Comment by naveennvrgup** [comment]
closed because it not relevant.

**Pull request closed without merging**
